baseURL = "https://www.corporatesoftware.ch"
defaultContentLanguage = "de"
disableLanguages = ["fr", "en"]
paginate = "6"
summaryLength = "10"
theme = "hugo-theme-copper"
title = "CoSo - Preview Homepage"
[Languages.de]
contentDir = "content/german"
languageCode = "de-ch"
languageName = "De"
[[Languages.de.menu.main]]
hasChildren = true
name = "Services"
weight = 1
[[Languages.de.menu.main]]
URL = "services/data-ai"
name = "Data & AI"
parent = "Services"
[[Languages.de.menu.main]]
URL = "services/automation"
name = "Automation"
parent = "Services"
[[Languages.de.menu.main]]
URL = "services/collaboration"
name = "Collaboration"
parent = "Services"
[[Languages.de.menu.main]]
URL = "success"
name = "Erfolge"
weight = 2
[[Languages.de.menu.main]]
hasChildren = true
name = "COSOverse"
weight = 3
[[Languages.de.menu.main]]
URL = "team"
name = "Team"
parent = "COSOverse"
weight = 2
[[Languages.de.menu.main]]
URL = "certified-quality"
name = "Zertifizierte Qualität"
parent = "COSOverse"
weight = 4
[[Languages.de.menu.main]]
URL = "jobs"
name = "Jobs"
parent = "COSOverse"
weight = 3
[[Languages.de.menu.main]]
URL = "about"
name = "Über uns"
parent = "COSOverse"
weight = 1
[[Languages.de.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.de.menu.main]]
URL = "contact"
name = "Kontakt"
weight = 6
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
appinsights_instrumentationkey = "f6f701e5-fd55-4628-9671-2d421f641d74"
author = "Thomas"
contact_form_action = "#"
description = "CoSo begeistert als Schweizer Unternehmen seit 2011 Kund:innen mit nachhaltigen Lösungskonzepten an der Schnittstelle zwischen Business und IT. Wir arbeiten in und mit der Microsoft Cloud."
logo = "images/logo.png"
logo_cc = "images/logo_cc.png"
[params.mspartner]
image = "/uploads/ms-partner-animiert.gif"
link = "https://partnercenter.microsoft.com/de-de/pcv/solution-providers/corporate-software-ag_2bbd7e41-02c9-4b4e-8168-339f900c4319/03808051-21e7-4f9a-b24c-52f17fa5d0f7"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[params.preloader]
enable = false
preloader = "images/logo_cc.png"
[[params.social]]
icon = "ti-microsoft"
link = "https://partnercenter.microsoft.com/de-de/pcv/solution-providers/corporate-software-ag_2bbd7e41-02c9-4b4e-8168-339f900c4319/03808051-21e7-4f9a-b24c-52f17fa5d0f7"
name = "Microsoft Solution Provider"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/corporate-software/"
name = "LinkedIn"
[[params.social]]
icon = "ti-meetup"
link = "https://www.meetup.com/de-DE/AI-and-Intelligent-Cloud"
name = "MeetUp"
[[params.social]]
icon = "ti-kununu"
link = "https://www.kununu.com/ch/corporate-software1"
name = "Kununu"
