######################## default configuration ####################
baseURL = "https://coso.azureedge.net"
title = "CoSo - Preview Homepage"
theme = "hugo-theme-copper"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com

defaultContentLanguage = "de"

# disable language
disableLanguages = ["fr", "en"] # desable language from here


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Thomas"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "images/logo_cc.png" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
name = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
name = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
name = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"



################################### German language #####################################
[Languages.de]
languageName = "De"
languageCode = "de-ch"
contentDir = "content/german"
weight = 1
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"


############### German navigation ################
# main menu
[[Languages.de.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.de.menu.main]]
name = "Über uns"
URL = "about"
weight = 2

[[Languages.de.menu.main]]
name = "Service"
URL = "service"
weight = 3

[[Languages.de.menu.main]]
name = "Team"
URL = "team"
weight = 4

[[Languages.de.menu.main]]
name = "Kontakt"
URL = "contact"
weight = 5

[[Languages.de.menu.main]]
name = "Sonstiges"
weight = 6
hasChildren = true

  [[Languages.de.menu.main]]
  parent = "Sonstiges"
  name = "Career"
  URL = "career"

  [[Languages.de.menu.main]]
  parent = "Sonstiges"
  name = "Pricing"
  URL = "pricing"
  
  [[Languages.de.menu.main]]
  parent = "Sonstiges"
  name = "Pricing 2"
  URL = "pricing-2"

# Footer menu
[[Languages.de.menu.footer]]
name = "Faq"
URL = "faq"
weight = 1

[[Languages.de.menu.footer]]
name = "Terms & Conditions"
URL = "terms-conditions"
weight = 2

[[Languages.de.menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 3