---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Hauptkonfiguration
- type: document
  path: data/de/homepage.yml
  label: Seitenkonfiguration
- type: directory
  path: content/german/services
  label: Services
  create: documents
  match: "**/*"
  templates:
  - service
- type: document
  path: content/german/about/_index.md
  label: Über uns
- type: directory
  path: content/german/jobs
  label: Jobs
  create: documents
  match: "**/*"
  templates:
  - job-ausschreibung
- type: document
  path: content/german/success/_index.md
  label: Erfolge Seite
- type: directory
  path: content/german/success
  label: Erfolgsgeschichten
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - success-story
- type: document
  path: content/german/blog/_index.md
  label: Blog Seite
- type: directory
  path: content/german/blog
  label: Blogbeiträge
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blogbeitrag
- type: directory
  path: content/german/team
  label: Team
  create: documents
  match: "**/*"
  templates:
  - teammitglied
- type: document
  path: content/german/contact/_index.md
  label: Kontakt
- type: document
  path: data/de/partner.yml
  label: Partner
- type: document
  path: i18n/de.yaml
  label: Sprachelemente
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
