---
label: Service
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Titel
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Beschreibung
- name: image
  type: file
  config:
    maxSize: 64
  label: Bild
