# This is a basic workflow to help you get started with Actions

name: Translate-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ staging ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  translate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install azcopy
        uses: kheiakiyama/install-azcopy-action@v1.0.3
        with:
          version: 'v10'

      - name: Copy Files to Azure Storage
        run: azcopy copy "content/german/*" "${{ secrets.STORAGE_GERMAN_CONNECTION_STRING }}" --recursive=true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

       #- name: Pip Installer
         #uses: BSFishy/pip-action@v1
         #with:
           #packages: |
             #requests
             #azure-storage-blob

       #- name: Execute Python Script # run the run.py to get the latest data
        #run: |
        #  python script/translate.py
         #env:
           #service_key: ${{ secrets.COGSERV_KEY }}
           #storage_key: ${{ secrets.STORAGE_KEY }}
           #cs_german: ${{ secrets.STORAGE_GERMAN_CONNECTION_STRING }} 
           #cs_english: ${{ secrets.STORAGE_ENGLISH_CONNECTION_STRING }} 
           #cs_french: ${{ secrets.STORAGE_FRENCH_CONNECTION_STRING }} 
           #location: switzerlandnorth
           #service_name: cosowebtranslator

      - name: Download Translations
        run: azcopy copy "${{ secrets.STORAGE_ENGLISH_CONNECTION_STRING }}" "content/" --recursive=true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: translated
          title: Translation Complete
          body: Translation is complete
          branch: translated


